spring:
  application:
    name: weather-service

server:
  servlet:
    context-path: /weather
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true